#!/usr/bin/env bash
# Regenerate evidence only in a disposable, platform-matched clone.
set -euo pipefail

root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
test "$(uname -s)" = Darwin || { echo "producer regeneration requires Darwin" >&2; exit 1; }
test "$(uname -m)" = arm64 || { echo "producer regeneration requires darwin/arm64" >&2; exit 1; }
python3 - <<'PY'
import sys
if sys.version_info[:2] != (3, 13):
    raise SystemExit("producer regeneration requires Python 3.13")
PY
git -C "$root" diff --quiet && git -C "$root" diff --cached --quiet && test -z "$(git -C "$root" status --porcelain --untracked-files=all)" || {
  echo "regeneration refuses a dirty source checkout" >&2; exit 1;
}
work=$(mktemp -d "${TMPDIR:-/tmp}/agent-governance-regenerate.XXXXXX")
trap 'rm -rf "$work"' EXIT
git clone --quiet --no-local "$root" "$work/source"
cd "$work/source"
generated_file_list="$work/generated-files"
git ls-files 'fixtures/evidence/agt/**' 'fixtures/evidence/non-agt/**' > "$generated_file_list"
test -s "$generated_file_list" || { echo "no generated fixtures found" >&2; exit 1; }
mkdir "$work/expected"
while IFS= read -r file; do
  mkdir -p "$work/expected/$(dirname "$file")"
  cp "$file" "$work/expected/$file"
  rm "$file"
done < "$generated_file_list"
./adapters/agt/setup.sh
./adapters/agt/.venv/bin/pip check
./adapters/non-agt/producer.py
./adapters/agt/.venv/bin/python ./adapters/agt/producer.py
LC_ALL=C sort "$generated_file_list" > "$work/expected-files"
find fixtures/evidence -type f -print | sed 's#^\./##' | LC_ALL=C sort > "$work/actual-files"
cmp -s "$work/expected-files" "$work/actual-files" || { echo "generated evidence file set drifted" >&2; exit 1; }
while IFS= read -r file; do cmp -s "$file" "$work/expected/$file" || { echo "generated bytes drifted: $file" >&2; exit 1; }; done < "$generated_file_list"
git diff --exit-code -- adapters fixtures policy/agent_governance.rego internal/evidence/schemas checkpoint.sha256.json LICENSE
go run ./cmd/checkpoint -root . -verify
